name: Reusable Lint Python

on:
  workflow_call:
    inputs:
      pyProjectDirectory:
        default: "pyproject.toml"
        required: false
        type: string
        description: "Path to pyproject.toml"
      checkBlack:
        required: false
        type: boolean
        default: true
        description: "Enable Black formatter check"
      checkFlake8:
        required: false
        type: boolean
        default: true
        description: "Enable Flake8 linter"
      checkIsort:
        required: false
        type: boolean
        default: true
        description: "Enable isort import sorting"
      checkInterrogate:
        required: false
        type: boolean
        default: true
        description: "Enable docstring coverage"
      checkDarglint:
        required: false
        type: boolean
        default: true
        description: "Enable docstring style check"
      checkMypy:
        required: false
        type: boolean
        default: true
        description: "Enable type checking"
      checkDocformatter:
        required: false
        type: boolean
        default: true
        description: "Enable docstring formatter"
      checkPylint:
        required: false
        type: boolean
        default: true
        description: "Enable Pylint analysis"
      checkSortRequirements:
        required: false
        type: boolean
        default: true
        description: "Enable requirements sorting"
      python-version:
        required: false
        type: string
        default: "['3.10']"
        description: "Python version matrix"
      caching-key:
        required: false
        type: string
        default: "cache-main-venv-dependencies"
        description: "Cache key for dependencies"
      pip-install-command:
        required: false
        type: string
        default: "pip install -r requirements.txt"
        description: "Pip install command"
      requirements-directory:
        required: false
        type: string
        default: "requirements.txt"
        description: "Path to requirements.txt"
    secrets:
      GIT_TOKEN:
        required: false

jobs:
  lint_validator:
    runs-on: ubuntu-22.04
    name: Lint Validator

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Check Requirements Changed
        id: check_requirements
        run: |
          set +e
          git fetch origin main
          git diff --quiet origin/main -- ${{ inputs.requirements-directory }} 1>/dev/null
          if [[ $? == "0" ]]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get Changed Python Files
        id: changed_files
        run: |
          set +e
          changed_files=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/main) HEAD | grep ".*\.py$")
          if [ ! -z "$changed_files" ]; then
            changed_files=$(echo $changed_files | tr '\n' ' ')
            echo "files=$changed_files" >> "$GITHUB_OUTPUT"
          else
            echo "files=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ fromJson(inputs.python-version)[0] }}

      - name: Cache Dependencies
        if: steps.check_requirements.outputs.changed == 'false' && steps.changed_files.outputs.files != '0'
        id: cache
        uses: actions/cache@v4.0.0
        with:
          path: venv
          key: ${{ inputs.caching-key }}
          restore-keys: ${{ inputs.caching-key }}

      - name: Configure Virtualenv
        if: steps.cache.outputs.cache-hit != 'true' || steps.check_requirements.outputs.changed == 'true'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          ${{ inputs.pip-install-command }}

      - name: Restore Virtualenv
        run: |
          echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Run Black
        if: inputs.checkBlack && steps.changed_files.outputs.files != '0'
        run: black --check --config ${{ inputs.pyProjectDirectory }} ${{ steps.changed_files.outputs.files }}

      - name: Run Flake8
        if: inputs.checkFlake8 && always() && steps.changed_files.outputs.files != '0'
        run: flake8 --color always --extend-ignore DAR --toml-config ${{ inputs.pyProjectDirectory }} ${{ steps.changed_files.outputs.files }}

      - name: Run Isort
        if: inputs.checkIsort && always() && steps.changed_files.outputs.files != '0'
        run: isort --check-only --sp ${{ inputs.pyProjectDirectory }} --color --diff ${{ steps.changed_files.outputs.files }}

      - name: Run Interrogate
        if: inputs.checkInterrogate && always() && steps.changed_files.outputs.files != '0'
        run: interrogate --config ${{ inputs.pyProjectDirectory }} ${{ steps.changed_files.outputs.files }}

      - name: Run Darglint
        if: inputs.checkDarglint && always() && steps.changed_files.outputs.files != '0'
        run: darglint --verbosity 2 ${{ steps.changed_files.outputs.files }}

      - name: Run Mypy
        if: inputs.checkMypy && always() && steps.changed_files.outputs.files != '0'
        run: |
          mypy --config-file ${{ inputs.pyProjectDirectory }} ${{ steps.changed_files.outputs.files }} | mypy-gh-action-report | grep -v note
          exit 0

      - name: Run Docformatter
        if: inputs.checkDocformatter && always() && steps.changed_files.outputs.files != '0'
        run: docformatter --config ${{ inputs.pyProjectDirectory }} --exclude venv conda-env --recursive --check ${{ steps.changed_files.outputs.files }}

      - name: Run Pylint
        if: inputs.checkPylint && always() && steps.changed_files.outputs.files != '0'
        run: pylint --rcfile ${{ inputs.pyProjectDirectory }} ${{ steps.changed_files.outputs.files }}

      - name: Run Sort Requirements
        if: inputs.checkSortRequirements && always() && steps.changed_files.outputs.files != '0'
        run: sort-requirements --check ${{ inputs.requirements-directory }}
